testName: 7c2813a1-e07f-434d-8abf-7fca77cd66a5
testPlan: SampleTest2.jmx
description: 'Test plan reusado'
engineInstances: 4
failureCriteria: 
    - avg(response_time_ms) > 15
    - percentage(error) > 40
